# Generated by Django 4.0.3 on 2023-03-09 14:26

from django.db import migrations, models
import shellfishapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shellfishapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crab_ImageInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrabID', models.IntegerField()),
                ('ScientificName', models.CharField(max_length=500)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to=shellfishapp.models.filepath)),
                ('Image2', models.ImageField(blank=True, null=True, upload_to=shellfishapp.models.filepath)),
                ('Image3', models.ImageField(blank=True, null=True, upload_to=shellfishapp.models.filepath)),
            ],
            options={
                'db_table': 'Crab_image',
            },
        ),
        migrations.CreateModel(
            name='Crab_MorphologicalInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrabID', models.IntegerField()),
                ('ScientificName', models.CharField(max_length=100)),
                ('ShortDescription', models.TextField(blank=True, max_length=2000)),
                ('BodyNature', models.TextField(blank=True, max_length=2000)),
                ('Eyes', models.CharField(blank=True, max_length=500)),
                ('CarapaceNature', models.CharField(blank=True, max_length=500)),
                ('AntennalSegments', models.CharField(blank=True, max_length=500)),
                ('ChilepedNature', models.CharField(blank=True, max_length=500)),
                ('TelsonNature', models.CharField(blank=True, max_length=500)),
                ('SexualDimorphism', models.CharField(blank=True, max_length=500)),
                ('HabitatAndEcology', models.CharField(blank=True, max_length=500)),
                ('Biology', models.CharField(blank=True, max_length=500)),
                ('SpecificRemarks', models.CharField(blank=True, max_length=500)),
                ('Colouration', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'db_table': 'crab_morphological',
            },
        ),
        migrations.CreateModel(
            name='Crab_OccurrenceInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrabID', models.IntegerField()),
                ('ScientificName', models.CharField(max_length=500)),
                ('Locality', models.CharField(blank=True, max_length=500)),
                ('State', models.CharField(blank=True, max_length=500)),
                ('Latitude', models.CharField(blank=True, max_length=500)),
                ('Longitude', models.CharField(blank=True, max_length=500)),
                ('Source', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'crab_occurrence',
            },
        ),
       
        migrations.CreateModel(
            name='Crab_TypeSpecimenInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrabID', models.IntegerField()),
                ('ScientificName', models.CharField(max_length=500)),
                ('TypeSpecimen', models.CharField(blank=True, max_length=500)),
                ('Geo_Unit_Locality', models.CharField(blank=True, max_length=500)),
                ('Descriptor', models.CharField(blank=True, max_length=500)),
                ('SpecimenCatalogueNumber', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'crab_typespecimen',
            },
        ),
        
    ]
