# Generated by Django 4.0.3 on 2023-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellfishapp', '0002_crab_imageinsert_crab_morphologicalinsert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crab_imageinsert',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='crab_imageinsert',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='crab_imageinsert',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
