# Generated by Django 4.0.3 on 2023-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellfishapp', '0005_imageinsert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crab_TaxonmyDistributionInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kingdom', models.CharField(blank=True, max_length=500)),
                ('Phylum', models.CharField(blank=True, max_length=500)),
                ('SubPhylum', models.CharField(blank=True, max_length=500)),
                ('Class', models.CharField(blank=True, max_length=500)),
                ('SubClass', models.CharField(blank=True, max_length=500)),
                ('SuperOrder', models.CharField(blank=True, max_length=500)),
                ('Order', models.CharField(blank=True, max_length=500)),
                ('SubOrder', models.CharField(blank=True, max_length=500)),
                ('InfraOrder', models.CharField(blank=True, max_length=500)),
                ('SuperFamily', models.CharField(blank=True, max_length=500)),
                ('Family', models.CharField(blank=True, max_length=500)),
                ('SubFamily', models.CharField(blank=True, max_length=500)),
                ('Genus', models.CharField(blank=True, max_length=500)),
                ('ScientificName', models.CharField(blank=True, max_length=500)),
                ('TaxonomicRank', models.CharField(blank=True, max_length=500)),
                ('Subspecies', models.CharField(blank=True, max_length=500)),
                ('AcceptedValidName', models.TextField(blank=True, max_length=500)),
                ('CommonName', models.CharField(blank=True, max_length=500)),
                ('Author', models.CharField(blank=True, max_length=500)),
                ('MainReference', models.TextField(blank=True, max_length=500)),
                ('Environment', models.CharField(blank=True, max_length=500)),
                ('ConservationStatus', models.CharField(blank=True, max_length=500)),
                ('DistributionInIndia', models.TextField(blank=True, max_length=1000)),
                ('DistributionOutsideOfIndia', models.TextField(blank=True, max_length=1000)),
                ('PopulationStatus', models.CharField(blank=True, max_length=500)),
                ('OriginType', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'crab_taxonmydistribution',
            },
        ),
    ]
