# Generated by Django 4.0.3 on 2023-04-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellfishapp', '0006_crab_taxonmydistributioninsert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crab_SynonymsInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrabID', models.IntegerField()),
                ('ScientificName', models.CharField(max_length=500)),
                ('Synonym', models.CharField(blank=True, max_length=500)),
                ('Synonymy', models.CharField(blank=True, max_length=500)),
                ('Status', models.CharField(blank=True, max_length=500)),
                ('Valid', models.CharField(blank=True, max_length=500)),
                ('Author', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'crab_synonyms',
            },
        ),
    ]
