# Generated by Django 4.0.3 on 2023-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellfishapp', '0007_crab_synonymsinsert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobster_TaxonmyDistributionInsert',
            fields=[
                ('LobsterID', models.AutoField(primary_key=True, serialize=False)),
                ('Kingdom', models.CharField(blank=True, max_length=500, null=True)),
                ('Phylum', models.CharField(blank=True, max_length=500, null=True)),
                ('SubPhylum', models.CharField(blank=True, max_length=500, null=True)),
                ('Class', models.CharField(blank=True, max_length=500, null=True)),
                ('SubClass', models.CharField(blank=True, max_length=500, null=True)),
                ('SuperOrder', models.CharField(blank=True, max_length=500, null=True)),
                ('Order', models.CharField(blank=True, max_length=500, null=True)),
                ('SubOrder', models.CharField(blank=True, max_length=500, null=True)),
                ('InfraOrder', models.CharField(blank=True, max_length=500, null=True)),
                ('SuperFamily', models.CharField(blank=True, max_length=500, null=True)),
                ('Family', models.CharField(blank=True, max_length=500, null=True)),
                ('SubFamily', models.CharField(blank=True, max_length=500, null=True)),
                ('Genus', models.CharField(blank=True, max_length=500, null=True)),
                ('ScientificName', models.CharField(blank=True, max_length=500, null=True)),
                ('TaxonomicRank', models.CharField(blank=True, max_length=500, null=True)),
                ('Subspecies', models.CharField(blank=True, max_length=500, null=True)),
                ('AcceptedValidName', models.TextField(blank=True, max_length=500, null=True)),
                ('CommonName', models.CharField(blank=True, max_length=500, null=True)),
                ('Author', models.CharField(blank=True, max_length=500, null=True)),
                ('MainReference', models.TextField(blank=True, max_length=500, null=True)),
                ('Environment', models.CharField(blank=True, max_length=500, null=True)),
                ('ConservationStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('DistributionInIndia', models.TextField(blank=True, max_length=1000, null=True)),
                ('DistributionOutsideOfIndia', models.TextField(blank=True, max_length=1000, null=True)),
                ('PopulationStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('OriginType', models.TextField(blank=True, max_length=1000, null=True)),
                ('DepthRange', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'lobster_taxonmydistribution',
            },
        ),
    ]
